services:
  - type: web
    name: your-php-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    disk:
      name: persistent-storage
      mountPath: /var/www/html
    buildCommand: "docker build --no-cache -t your-php-app ."
    startCommand: "apache2-foreground"
    envVars:
      - key: DATABASE_URL
        sync: false  # Set this manually in Render Dashboard
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: "/var/www/html/service-account.json"  # Ensures API credentials are available
    healthCheckPath: "/"
    autoDeploy: true
